name: Metrics AniList

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write   # <- necesario para hacer commits

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics.plugin.anilist.svg
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: "tu_usuario_anilist"
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
