name: 📅 Isometric Commit Calendar

on:
  # Ejecuta el workflow cada 24h
  schedule:
    - cron: "0 0 * * *"
  # Permite ejecutarlo manualmente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🧩 Generate half-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
 
